"""add_checkins_and_refund_requests

Revision ID: 3711fbb22d6c
Revises: 6a0428ce87c6
Create Date: 2026-02-28 02:00:56.706815

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '3711fbb22d6c'
down_revision: Union[str, None] = '6a0428ce87c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False, comment='签到日期'),
    sa.Column('points_earned', sa.Integer(), nullable=False, comment='本次签到获得积分'),
    sa.Column('streak_days', sa.Integer(), nullable=False, comment='连续签到天数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('refund_requests',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='退款原因'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/approved/rejected'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='管理员处理备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_requests_order_id'), 'refund_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_user_id'), 'refund_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_requests_user_id'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_order_id'), table_name='refund_requests')
    op.drop_table('refund_requests')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
