"""initial

Revision ID: 6a0428ce87c6
Revises: 
Create Date: 2026-02-26 01:10:55.779285

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '6a0428ce87c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False, comment='discount/flash_sale/gift/sign_in'),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('discount_rate', sa.DECIMAL(precision=4, scale=2), nullable=True, comment='折扣率，0.8=8折'),
    sa.Column('quota', mysql.INTEGER(unsigned=True), nullable=True, comment='参与限额，NULL不限'),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft/active/ended'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False, comment='创建管理员ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_participants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_products',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('apply_status', sa.String(length=20), nullable=False, comment='pending/approved/rejected'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('receiver_name', sa.String(length=50), nullable=False),
    sa.Column('receiver_phone', sa.String(length=11), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('is_default', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='NULL=草稿'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sku_id', name='uk_user_sku')
    )
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(unsigned=True), nullable=True, comment='父分类ID，NULL为一级'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False, comment='1:1 与 product_skus'),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False, comment='冗余，便于查询'),
    sa.Column('quantity', mysql.INTEGER(unsigned=True), nullable=False, comment='实际库存'),
    sa.Column('locked_quantity', mysql.INTEGER(unsigned=True), nullable=False, comment='已预占未发货'),
    sa.Column('low_stock_alert', mysql.INTEGER(unsigned=True), nullable=False, comment='低库存预警阈值'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('merchants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='关联 users.id'),
    sa.Column('merchant_name', sa.String(length=100), nullable=False, comment='商户名称'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=11), nullable=False),
    sa.Column('business_license', sa.String(length=500), nullable=True, comment='营业执照URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/approved/rejected'),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', mysql.BIGINT(unsigned=True), nullable=True, comment='审核管理员 user_id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='快照：商品名'),
    sa.Column('sku_name', sa.String(length=200), nullable=False, comment='快照：规格名'),
    sa.Column('cover_image', sa.String(length=500), nullable=False, comment='快照：主图'),
    sa.Column('points_price', mysql.INTEGER(unsigned=True), nullable=False, comment='快照：积分单价'),
    sa.Column('cash_supplement', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单号'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('merchant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('total_points', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('total_cash', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/paid/shipped/delivered/completed/cancelled/refunding/refunded'),
    sa.Column('receiver_name', sa.String(length=50), nullable=False, comment='快照：收件人'),
    sa.Column('receiver_phone', sa.String(length=11), nullable=False),
    sa.Column('receiver_address', sa.String(length=300), nullable=False, comment='快照：完整地址'),
    sa.Column('express_company', sa.String(length=50), nullable=True),
    sa.Column('express_no', sa.String(length=50), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('phone_recharge_orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('recharge_type', sa.String(length=10), nullable=False, comment='phone / flow'),
    sa.Column('phone_number', sa.String(length=11), nullable=False, comment='充值手机号'),
    sa.Column('package_name', sa.String(length=100), nullable=False, comment='套餐名称'),
    sa.Column('points_cost', mysql.INTEGER(unsigned=True), nullable=False, comment='消耗积分'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Demo中直接成功'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False, comment='register/recharge/exchange/refund/phone_recharge/flow_recharge/manual_add/manual_deduct'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='变化量（正=增加，负=减少）'),
    sa.Column('balance_after', mysql.INTEGER(unsigned=True), nullable=False, comment='操作后余额'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('ref_id', mysql.BIGINT(unsigned=True), nullable=True, comment='关联ID（order_id等）'),
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), nullable=True, comment='操作人（管理员）ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_rules',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False, comment='register / recharge_package'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('points_amount', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cash_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='充值套餐现金价（Demo均为0）'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False, comment='gallery/detail'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_skus',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_name', sa.String(length=200), nullable=False, comment='规格描述，如：红色/XL'),
    sa.Column('points_price', mysql.INTEGER(unsigned=True), nullable=False, comment='该规格积分价'),
    sa.Column('cash_supplement', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('merchant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='商品详情（富文本）'),
    sa.Column('cover_image', sa.String(length=500), nullable=False, comment='主图URL'),
    sa.Column('min_points', mysql.INTEGER(unsigned=True), nullable=False, comment='最低积分（列表展示用）'),
    sa.Column('cash_supplement', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True, comment='逗号分隔：精选,爆品,新品'),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='on_sale/off_shelf/pending'),
    sa.Column('total_sales', mysql.INTEGER(unsigned=True), nullable=False, comment='总销量'),
    sa.Column('review_count', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('good_review_rate', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='好评率'),
    sa.Column('is_self_operated', mysql.TINYINT(display_width=1), nullable=False, comment='是否自营（甄选）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rating', mysql.TINYINT(unsigned=True), nullable=False, comment='评分 1-5'),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('is_anonymous', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号（账号）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱（可选）'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'merchant', 'admin'), nullable=False, comment='角色'),
    sa.Column('points_balance', sa.Integer(), nullable=False, comment='积分余额（冗余）'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_banned', mysql.TINYINT(display_width=1), nullable=False, comment='是否封禁'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('products')
    op.drop_table('product_skus')
    op.drop_table('product_images')
    op.drop_table('points_rules')
    op.drop_table('points_records')
    op.drop_table('phone_recharge_orders')
    op.drop_table('orders')
    op.drop_table('order_items')
    op.drop_table('merchants')
    op.drop_table('inventory')
    op.drop_table('categories')
    op.drop_table('cart_items')
    op.drop_table('announcements')
    op.drop_table('addresses')
    op.drop_table('activity_products')
    op.drop_table('activity_participants')
    op.drop_table('activities')
    # ### end Alembic commands ###
